project_id = "gpuospxsvakjuhaencsk"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-payment-proof-notification]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false
